export enum GameEvent {
    ASSETS_LOADED = "ASSETS_LOADED",
    SHOW_TITLE_SCREEN = "SHOW_TITLE_SCREEN",
    SHOW_GAME_SCREEN = "SHOW_GAME_SCREEN",
    SPIN_REQUESTED = "SPIN_REQUESTED",
    SPIN_RESULT_RECEIVED = "SPIN_RESULT_RECEIVED",
    SPIN_COMPLETE = "SPIN_COMPLETE",
    GAME_DATA_RECEIVED = "GAME_DATA_RECEIVED"
}

// TODO - Can we add further typing to the events with payloads?